name: ci
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest']
        ruby-version: ['2.7', '3.1', '3.3']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: ruby/setup
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2
          bundler-cache: false
          rubygems: latest

      - name: Install dependencies
        run: bundle install

      - name: Tests
        run: bin/test
